apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-gitops-lab

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: NGINX_GITOPS_IMAGE
    newName: 451638006344.dkr.ecr.us-east-1.amazonaws.com/nginx-gitops-lab
    newTag: initial
