apiVersion: v1
kind: Service
metadata:
  name: nginx-gitops-lab
  namespace: nginx-gitops
spec:
  type: ClusterIP

  selector:
    app: nginx-gitops-lab

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
